# Generated by Django 5.1.6 on 2025-03-09 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RadioClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('needs_repair', 'Needs Repair')], default='good', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('total_slots', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StorageSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('charging', 'Charging'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('radioclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='storage.radioclass')),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='storage.storageunit')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_tag', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_guimc_member', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='storage.group')),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField()),
                ('is_access_granted', models.BooleanField(default=False)),
                ('radioclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.radioclass')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.storageslot')),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storageunit')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='storage.student')),
            ],
        ),
    ]
