# Generated by Django 5.1.6 on 2025-03-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_remove_student_is_guimc_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageunit',
            name='total_slots',
        ),
    ]
