# Generated by Django 5.1.6 on 2025-03-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_remove_storageunit_total_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='rfid_tag_attempted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
