# Generated by Django 5.1.6 on 2025-03-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_accesslog_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='access',
            field=models.BooleanField(default=False),
        ),
    ]
