# Generated by Django 5.1.6 on 2025-05-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_student_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radioclass',
            name='condition',
        ),
        migrations.AddField(
            model_name='radioclass',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='radioclass',
            name='status',
            field=models.CharField(choices=[('charged', 'Заряжен'), ('charging', 'Заряжается'), ('unplugged', 'Не подключен')], default='Не подключен', max_length=20),
        ),
    ]
