# Generated by Django 5.1.6 on 2025-06-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_remove_radioclass_condition_radioclass_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageslot',
            name='status',
            field=models.CharField(choices=[('available', 'Доступно'), ('occupied', 'Занято'), ('unavailable', 'Недоступно')], default='available', max_length=20),
        ),
    ]
